name_prefix: "ddpg_ip_bc"
project: "ddpg_ip_bc"
env: "inverted_pendulum"
benchmark: ["V1", "V2", "V3"]

ablations:
  lr: [0.00025]
  behavior_cloning_coefficient: [0.1]
  seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
