#!/usr/bin/env python3
"""
Compute aggregated min-ACC for k=3 (Task 3) for RL ablation experiments.
Normalized to a 0-100 scale relative to the maximum score achieved.

AGGREGATION UPDATE:
This script aggregates by timestep FIRST across seeds (using Mean or IQM),
and THEN computes the max and min on the resulting aggregated learning curve.

Follows the definition from "Continual evaluation for lifelong learning":
  1. For k=3, the previous tasks are i=1 and i=2 (indexes 0 and 1).
  2. Extract full learning curves for each previous task i up to task k.
  3. Aggregate the learning curves across seeds at each timestep.
  4. On the aggregated curve:
     a) Find the maximum accuracy achieved throughout training.
     b) Find the absolute minimum accuracy during the training of tasks i+1 through k.
     c) Normalized min-ACC_i = (min_score_i / max_score_i) * 100
  5. Average across tasks: min-ACC(T_k) = (1 / (k-1)) * sum_i Normalized_min_ACC_i
  6. Confidence intervals are generated by bootstrapping the seed resampling before aggregation.

Usage:
  python compute_min_acc.py --config dispatch/experiments/cartpole/dqn_cp_bc.yaml
  python compute_min_acc.py --config dispatch/experiments/cartpole/dqn_cp_bc.yaml --iqm
"""

import argparse
import itertools
import sys
from pathlib import Path

import numpy as np
import pandas as pd

try:
    import yaml
except ImportError:
    print("PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

DATA_DIR = Path(__file__).resolve().parent.parent / "output" / "output"
N_BOOTSTRAP = 10_000
CONFIDENCE = 0.90


# ---------------------------------------------------------------------------
# Value formatting
# ---------------------------------------------------------------------------

def format_value(val) -> str:
    """Format a hyperparameter value the same way dispatch_yaml.py does for filenames."""
    if isinstance(val, float):
        if val.is_integer():
            return str(int(val))
        else:
            return str(val).rstrip("0").rstrip(".").replace(".", "")
    if isinstance(val, str) and "." in val:
        try:
            f_val = float(val)
            if f_val.is_integer():
                return str(int(f_val))
            else:
                return str(f_val).rstrip("0").rstrip(".").replace(".", "")
        except ValueError:
            pass
    return str(val)


# ---------------------------------------------------------------------------
# Config parsing
# ---------------------------------------------------------------------------

def parse_config(config_path: str) -> dict:
    with open(config_path) as f:
        cfg = yaml.safe_load(f)

    ablations = cfg.get("ablations", {})
    benchmark = cfg.get("benchmark", [])
    name_prefix = cfg.get("name_prefix", "experiment")

    all_ablation_keys = list(ablations.keys())

    seeds = ablations.get("seed", [0])
    if not isinstance(seeds, list):
        seeds = [seeds]

    hp_keys = [k for k in all_ablation_keys if k != "seed"]
    hp_values = [ablations[k] if isinstance(ablations[k], list) else [ablations[k]] for k in hp_keys]

    return {
        "name_prefix": name_prefix,
        "benchmark": benchmark,
        "seeds": seeds,
        "hp_keys": hp_keys,
        "hp_values": hp_values,
        "all_ablation_keys": all_ablation_keys,
    }


def enumerate_combinations(cfg: dict):
    if not cfg["hp_keys"]:
        yield {}
        return
    for combo in itertools.product(*cfg["hp_values"]):
        yield dict(zip(cfg["hp_keys"], combo))


def build_suffix(hp_combo: dict, seed: int, all_ablation_keys: list[str]) -> str:
    parts = []
    for k in all_ablation_keys:
        v = seed if k == "seed" else hp_combo[k]
        parts.append(f"{k[0]}_{format_value(v)}")
    return "-".join(parts)


# ---------------------------------------------------------------------------
# Main Computation: Timestep Aggregation & Bootstrap
# ---------------------------------------------------------------------------

def compute_all(cfg: dict, k_idx: int, data_dir: Path, use_iqm: bool = False) -> pd.DataFrame:
    benchmark = cfg["benchmark"]
    seeds = cfg["seeds"]
    name_prefix = cfg["name_prefix"]
    all_ablation_keys = cfg["all_ablation_keys"]

    rows = []

    for hp_combo in enumerate_combinations(cfg):

        # We collect the full time-series for each evaluation task i
        valid_seeds = []
        seed_data_collection = {benchmark[i]: [] for i in range(k_idx)}
        phase_boundaries = {benchmark[i]: None for i in range(k_idx)}

        for seed in seeds:
            seed_valid = True
            temp_seed_data = {}
            temp_boundaries = {}

            suffix = build_suffix(hp_combo, seed, all_ablation_keys)

            for i in range(k_idx):
                eval_env = benchmark[i]
                curve_parts = []
                lengths = []

                # Fetch trajectory points from task i up to task k
                for j in range(i, k_idx + 1):
                    train_env = benchmark[j]
                    filename = f"{name_prefix}-{suffix}-{train_env}.csv"
                    filepath = data_dir / name_prefix / filename

                    if not filepath.exists() or filepath.stat().st_size == 0:
                        seed_valid = False
                        break

                    try:
                        df = pd.read_csv(filepath)
                        reward_col = f"eval/{eval_env}/mean_reward"
                        if reward_col not in df.columns:
                            seed_valid = False
                            break

                        vals = df[reward_col].dropna().values
                        if len(vals) == 0:
                            seed_valid = False
                            break

                        curve_parts.append(vals)
                        lengths.append(len(vals))
                    except Exception:
                        seed_valid = False
                        break

                if not seed_valid:
                    break

                temp_seed_data[eval_env] = np.concatenate(curve_parts)
                # the index where task i+1 starts is exactly the length of task i (which is lengths[0])
                temp_boundaries[eval_env] = lengths[0]

            if seed_valid:
                valid_seeds.append(seed)
                for i in range(k_idx):
                    eval_env = benchmark[i]
                    seed_data_collection[eval_env].append(temp_seed_data[eval_env])
                    if phase_boundaries[eval_env] is None:
                        phase_boundaries[eval_env] = temp_boundaries[eval_env]

        if len(valid_seeds) == 0:
            row = dict(hp_combo)
            row["n_seeds_found"] = 0
            row["min-ACC_stat"] = np.nan
            row["min-ACC_ci_low"] = np.nan
            row["min-ACC_ci_high"] = np.nan
            rows.append(row)
            continue

        # Ensure uniform lengths (truncate to the minimum sequence length observed)
        stacked_curves = {}
        for i in range(k_idx):
            eval_env = benchmark[i]
            min_len = min(len(c) for c in seed_data_collection[eval_env])
            stacked_curves[eval_env] = np.array([c[:min_len] for c in seed_data_collection[eval_env]])
            phase_boundaries[eval_env] = min(phase_boundaries[eval_env], min_len)

        # Precompute IQM slice boundaries
        n_valid = len(valid_seeds)
        lowercut = int(0.25 * n_valid)
        uppercut = n_valid - lowercut
        do_iqm_trim = use_iqm and lowercut > 0 and uppercut > lowercut

        # Helper function: aggregates curves based on provided 2D seed indices, then computes min-ACC
        def calc_metric_vectorized(seed_indices_2d):
            # seed_indices_2d shape: (N, n_valid) where N is batch size
            N = seed_indices_2d.shape[0]
            task_accs = np.zeros((k_idx, N))

            for i in range(k_idx):
                eval_env = benchmark[i]
                # curves shape: (N, n_valid, num_timesteps)
                curves = stacked_curves[eval_env][seed_indices_2d]

                # Aggregate by timestep across the sampled seeds (axis=1)
                if do_iqm_trim:
                    # Use np.partition (O(n)) instead of full sort (O(n log n))
                    # We need elements in positions [lowercut, uppercut) along axis=1
                    # Partition at uppercut-1 ensures elements < uppercut are in the left partition
                    curves = np.partition(curves, uppercut - 1, axis=1)
                    # Now partition the left part at lowercut to isolate [lowercut, uppercut)
                    curves[:, :uppercut, :] = np.partition(
                        curves[:, :uppercut, :], lowercut, axis=1
                    )
                    agg_curve = np.mean(curves[:, lowercut:uppercut, :], axis=1)
                else:
                    agg_curve = np.mean(curves, axis=1)

                max_score = np.max(agg_curve, axis=1)
                start_idx = phase_boundaries[eval_env]
                min_score = np.min(agg_curve[:, start_idx:], axis=1)

                # Normalize relative to the peak performance (0-100 scale)
                max_score_safe = np.where(max_score > 0, max_score, 1.0)
                norm = (min_score / max_score_safe) * 100.0
                norm[max_score <= 0] = 0.0
                task_accs[i, :] = norm

            return np.mean(task_accs, axis=0)

        # 1. Compute observed statistic using all valid seeds
        observed_stat = calc_metric_vectorized(np.arange(n_valid)[None, :])[0]

        # 2. Bootstrap Confidence Interval — generate all indices upfront
        rng = np.random.default_rng(42)
        boot_indices = rng.integers(0, n_valid, size=(N_BOOTSTRAP, n_valid))
        boot_stats = calc_metric_vectorized(boot_indices)

        alpha = (1 - CONFIDENCE) / 2
        ci_low = np.percentile(boot_stats, 100 * alpha)
        ci_high = np.percentile(boot_stats, 100 * (1 - alpha))

        row = dict(hp_combo)
        row["n_seeds_found"] = n_valid
        row["min-ACC_stat"] = observed_stat
        row["min-ACC_ci_low"] = ci_low
        row["min-ACC_ci_high"] = ci_high
        rows.append(row)

    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Output formatting
# ---------------------------------------------------------------------------

def format_ci(stat: float, ci_low: float, ci_high: float, precision: int = 2) -> str:
    if np.isnan(stat):
        return "N/A"
    return f"{stat:.{precision}f} [{ci_low:.{precision}f}, {ci_high:.{precision}f}]"


def results_to_markdown(df: pd.DataFrame, cfg: dict, k_idx: int, use_iqm: bool = False) -> str:
    hp_keys = cfg["hp_keys"]
    metric_name = "IQM" if use_iqm else "Mean"

    lines = []
    lines.append(f"# Normalized Stability Gap (min-ACC {metric_name}) at Task k={k_idx + 1} — {cfg['name_prefix']}")
    lines.append("")
    lines.append(
        f"Seeds: {len(cfg['seeds'])} | Confidence: {CONFIDENCE * 100:.0f}% | Aggregation: {metric_name} by timestep")
    lines.append("")

    header_parts = [k for k in hp_keys] + [f"Norm min-ACC (k={k_idx + 1})", "Seeds"]
    lines.append("| " + " | ".join(header_parts) + " |")
    lines.append("| " + " | ".join(["---"] * len(header_parts)) + " |")

    df_sorted = df.sort_values("min-ACC_stat", ascending=True)

    for _, row in df_sorted.iterrows():
        parts = [str(row[k]) for k in hp_keys]
        parts.append(format_ci(row["min-ACC_stat"], row["min-ACC_ci_low"], row["min-ACC_ci_high"]))
        parts.append(str(int(row["n_seeds_found"])))
        lines.append("| " + " | ".join(parts) + " |")

    return "\n".join(lines)


def results_to_csv(df: pd.DataFrame, cfg: dict) -> pd.DataFrame:
    hp_keys = cfg["hp_keys"]
    out_rows = []
    df_sorted = df.sort_values("min-ACC_stat", ascending=True)

    for _, row in df_sorted.iterrows():
        out = {k: row[k] for k in hp_keys}
        out["min-ACC_stat"] = row["min-ACC_stat"]
        out["min-ACC_ci_low"] = row["min-ACC_ci_low"]
        out["min-ACC_ci_high"] = row["min-ACC_ci_high"]
        out["min-ACC_formatted"] = format_ci(
            row["min-ACC_stat"], row["min-ACC_ci_low"], row["min-ACC_ci_high"]
        )
        out["n_seeds"] = int(row["n_seeds_found"])
        out_rows.append(out)

    return pd.DataFrame(out_rows)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="Compute normalized min-ACC for k=3 (Task 3) after aggregating by timestep.",
    )
    parser.add_argument(
        "--config", type=str, required=True,
        help="Path to the YAML experiment config file.",
    )
    parser.add_argument(
        "--data_dir", type=str, default=None,
        help=f"Override the data directory (default: {DATA_DIR}).",
    )
    parser.add_argument(
        "--output_dir", type=str, default=None,
        help="Directory to save output files. If not set, prints to stdout only.",
    )
    parser.add_argument(
        "--confidence", type=float, default=CONFIDENCE,
        help=f"Confidence level for bootstrap CI (default: {CONFIDENCE}).",
    )
    parser.add_argument(
        "--mean", action="store_true",
        help="Compute Mean across seeds at each timestep before computing min-ACC (default is IQM).",
    )
    return parser.parse_args()


def main():
    global CONFIDENCE

    args = parse_args()
    CONFIDENCE = args.confidence
    use_iqm = not args.mean

    data_dir = Path(args.data_dir) if args.data_dir else DATA_DIR
    cfg = parse_config(args.config)

    k_target = 3
    k_idx = k_target - 1  # 0-indexed offset

    print(f"Config: {args.config}")
    print(f"  Name prefix:  {cfg['name_prefix']}")
    print(f"  Benchmark:    {cfg['benchmark']}")
    print(f"  Target Task:  k={k_target} ({cfg['benchmark'][k_idx] if len(cfg['benchmark']) > k_idx else 'N/A'})")
    print(f"  Seeds:        {cfg['seeds']}")
    print(f"  Confidence:   {CONFIDENCE * 100:.0f}%")
    print(f"  Aggregation:  {'IQM' if use_iqm else 'Mean'} by timestep")
    print()

    if len(cfg["benchmark"]) <= k_idx:
        print(f"Error: The benchmark needs at least {k_target} tasks to compute min-ACC at k={k_target}.",
              file=sys.stderr)
        sys.exit(1)

    df = compute_all(cfg, k_idx, data_dir, use_iqm=use_iqm)

    # Print Markdown table
    md = results_to_markdown(df, cfg, k_idx, use_iqm=use_iqm)
    print(md)
    print()

    # Save outputs if requested
    if args.output_dir:
        out_dir = Path(args.output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        suffix = "" if use_iqm else "_mean"
        md_path = out_dir / f"{cfg['name_prefix']}_min_acc_k{k_target}{suffix}.md"
        md_path.write_text(md)
        print(f"Saved Markdown: {md_path}")

        csv_df = results_to_csv(df, cfg)
        csv_path = out_dir / f"{cfg['name_prefix']}_min_acc_k{k_target}{suffix}.csv"
        csv_df.to_csv(csv_path, index=False)
        print(f"Saved CSV:      {csv_path}")


if __name__ == "__main__":
    main()